### ISSUE TITLE
🎯 쿠폰 발급 기능 구현

### ISSUE THREAD

**Issue by kyeumd** [f-lab-edu/infrun#11]
## 목표

쿠폰 발급 기능

## ToDo

- [ ] 강사는 쿠폰 개수와 유효기간, 할인율을 설정 후 발급
- [ ] 쿠폰은 유효기간, 시리얼 넘버, 할인율, 상태를 가짐
  - [ ] 상태는 등록 여부, 사용 여부 상태로 나뉨
