### ISSUE TITLE
🎯  회원 로그인 기능 구현

### ISSUE THREAD

**Issue by chicori3** [f-lab-edu/infrun#13]
## 목표

회원 로그인 기능

## ToDo

- [x] 회원 로그인 Email, 비밀번호 필수 입력
- [x] 로그인 요청 시 Email, 비밀번호 검증
- [x] 비밀번호는 암호화를 적용하여 대조
- [x] 로그인 실패 시 401 Unauthorized 예외 반환
- [x] 로그인 성공 시 200 OK 반환

## 고려사항

- [x] JWT, 세션?
- [x] Spring Security 도입 고려
- [x] 암호화 기능
