### ISSUE TITLE
🎯 회원가입 기능 구현

### ISSUE THREAD

**Issue by kyeumd** [f-lab-edu/infrun#2]
## 목표

회원 가입 기능

## ToDo

- [x] 회원가입 시 Email, 비밀번호, 닉네임을 입력
- [x] Email과 닉네임 중복 확인
  - [x] 중복이 있으면 404 Bad Request 반환
- [x] 비밀번호 암호화 적용
- [x] 회원가입 성공 시 201 Created 반환

## 고려사항

- 암호화 알고리즘
