### ISSUE TITLE
🎯 CI/CD 구성하기

### ISSUE THREAD

**Issue by chicori3** [f-lab-edu/infrun#3]
## 목표

CI/CD 환경 구축

## ToDo

- [ ] Github Action workflow 작성
- [ ] 클라우드 서비스에 웹 어플리케이션 배포
- [ ] 도커로 Spring 애플리케이션과 MySQL 컨테이너 환경 구성

## 고려사항

- 클라우드 환경 선정하기
