### ISSUE TITLE
🎯 쿠폰 등록 기능 구현

### ISSUE THREAD

**Issue by kyeumd** [f-lab-edu/infrun#7]
## 목표

쿠폰 등록 기능 구현

## ToDo

- [x] 회원이 쿠폰의 시리얼 넘버를 입력
- [x] 쿠폰이 등록 가능하면 200 OK 반환
- [x] 쿠폰이 등록 불가능하면 400 Bad Request 반환

## 고려사항

- 동시성 문제가 발생할 여지가 있음
